### ISSUE TITLE
New option '-r' not fully working yet

### ISSUE THREAD

**Issue by Quent42340** [jaagr/lemonbuddy#85] opened 2016-10-14 12:47 UTC
When you run two bars with the same config file with the `-r` option, and when you update your config file, sometimes both are reloaded, sometimes only one, sometimes none of them.

**Comment by jaagr** [comment] 2016-10-14 13:09
Thanks for reporting. I think this is caused by two conflicting inotify watches, but I will look into it. I'd recommend only using the `--reload` flag when setting up the bar.

**Comment by jaagr** [comment] 2016-11-18 17:51
Closing as the `-r` flag is marked a experimental.

**Closed by jaagr** 2016-11-18 17:51 UTC
