### ISSUE TITLE
Error when building (make install) Ubuntu 16.04

### ISSUE THREAD

**Issue by nullrndtx** [jaagr/lemonbuddy#112] opened 2016-10-21 15:07 UTC
[error]: http://i.imgur.com/Fxtwh33.png "Error"

**Comment by jaagr** [comment] 2016-10-23 20:33
What was the error?

**Comment by Capuno** [comment] 2016-10-25 08:32
![sudo make install error lemonbar](https://cloud.githubusercontent.com/assets/18151803/19678229/2ce27998-9a9d-11e6-98bb-cb5b17aa87a9.png)

I got this at building, the translation of the last past is:
```
2 errors generated.
lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:62: error on the instructions for the objective 'lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o'
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
CMakeFiles/Makefile2:303: error on the instructions for the objective 'lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all'
make[1]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
Makefile:127: error on the instructions for the objective 'all'
make: *** [all] Error 2
```

**Comment by jaagr** [comment] 2016-10-25 08:39
Looks like you are using an old version.

Make sure you grab the latest changes

~~~
$ git pull
$ git submodule update --init --recursive
~~~

**Comment by jaagr** [comment] 2016-10-25 08:45
Might also be easier to just remove the directory and redo the steps in the README

**Comment by Capuno** [comment] 2016-10-25 10:10
![seleccion_020](https://cloud.githubusercontent.com/assets/18151803/19681842/4cd66094-9aab-11e6-827d-c5961ca51aed.png)

just git cloned it now, with `git clone --branch 2.1.0 --recursive https://github.com/jaagr/lemonbuddy`

**Comment by jaagr** [comment] 2016-10-25 11:00
@Capuno what distro are you running?

**Comment by Capuno** [comment] 2016-10-25 11:15
Ubuntu Xenial

**Comment by jaagr** [comment] 2016-10-25 11:42
Do you have these packages installed?

- libc++-dev
- libc++abi-dev

Not 100% sure about the apt packages.. will try to get a wm up with ubuntu so I can test manually.. travis tests are currently broken.

**Comment by jaagr** [comment] 2016-10-25 19:17
Reverted the libc++ enforcement so you should be able to build like before. Close the issue if it works.

**Comment by Capuno** [comment] 2016-10-25 19:58
![seleccion_021](https://cloud.githubusercontent.com/assets/18151803/19701965/f20dbe16-9afd-11e6-8342-8a204a948e91.png)
Still not working, tried with the method in readme.me and with the build.sh script.

**Comment by jaagr** [comment] 2016-10-25 20:13
Can you show me the output from the cmake command

**Comment by Capuno** [comment] 2016-10-25 20:20
http://hastebin.com/raw/dezegabida

**Comment by jaagr** [comment] 2016-10-25 20:26
Looks OK... try:

`cmake -DCMAKE_CXX_COMPILER=g++ ..`

**Comment by Capuno** [comment] 2016-10-25 20:39
```
[ 91%] Building CXX object bin/CMakeFiles/lemonbuddy.dir/main.cpp.o
In file included from /home/capuno/i3-things/rice/lemonbuddy/include/components/config.hpp:8:0,
                 from /home/capuno/i3-things/rice/lemonbuddy/src/main.cpp:6:
/home/capuno/i3-things/rice/lemonbuddy/include/components/logger.hpp: In instantiation of ‘void lemonbuddy::v2_0_0::logger::output(lemonbuddy::v2_0_0::loglevel, std::__cxx11::string, Args ...) const [with Args = {}; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/capuno/i3-things/rice/lemonbuddy/include/components/logger.hpp:108:5:   required from ‘void lemonbuddy::v2_0_0::logger::info(std::__cxx11::string, Args ...) const [with Args = {}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/capuno/i3-things/rice/lemonbuddy/include/components/x11/tray.hpp:140:43:   required from here
/home/capuno/i3-things/rice/lemonbuddy/include/components/logger.hpp:157:12: error: format not a string literal and no format arguments [-Werror=format-security]
     dprintf(m_fd, (prefix + format + suffix + "\n").c_str(), convert(values)...);
            ^
cc1plus: all warnings being treated as errors
bin/CMakeFiles/lemonbuddy.dir/build.make:62: fallo en las instrucciones para el objetivo 'bin/CMakeFiles/lemonbuddy.dir/main.cpp.o'
make[2]: *** [bin/CMakeFiles/lemonbuddy.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:184: fallo en las instrucciones para el objetivo 'bin/CMakeFiles/lemonbuddy.dir/all'
make[1]: *** [bin/CMakeFiles/lemonbuddy.dir/all] Error 2
Makefile:127: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
```

Same error, fresh git clone with `cmake -DCMAKE_CXX_COMPILER=g++ ..` at lemonbuddy/build

**Comment by jaagr** [comment] 2016-10-25 20:43
oh I think I know what the problem is.. I will push a fix

**Comment by jaagr** [comment] 2016-10-25 20:48
2529ec0 should fix the build

**Comment by Capuno** [comment] 2016-10-25 20:59
Working now! thanks for the help! Love your work as I said in one issue before.

Also I cannot close the issue as im not OP
![seleccion_022](https://cloud.githubusercontent.com/assets/18151803/19704096/ad21352c-9b06-11e6-9723-ce6104190db3.png)

**Comment by jaagr** [comment] 2016-10-25 21:08
Awesome! Thanks man... A tip for the bars: use a fixed font to avoid gaps between the lines...

![2016-10-25-230449_450x60_scrot](https://cloud.githubusercontent.com/assets/3697186/19704441/f76ccfe6-9b07-11e6-8248-a1db3c1b09df.png)

**Closed by jaagr** 2016-10-25 21:08 UTC
