### ISSUE TITLE
error make

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [jaagr/lemonbuddy#154] opened 2016-11-08 21:51 UTC
errors make in debian
Scanning dependencies of target jsoncpp_lib_static
[  1%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
[  2%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o
/home/vh/lemonbuddy/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_value.cpp: In constructor ‘Json::Value::Value(Json::ValueType)’:
/home/vh/lemonbuddy/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_value.cpp:346:27: error: declaration of ‘empty’ shadows a member of 'this' [-Werror=shadow]
   static char const empty[] = "";
                           ^
cc1plus: all warnings being treated as errors
lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/build.make:86: ошибка выполнения рецепта для цели «lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o»
make[2]: *** [lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o] Ошибка 1
CMakeFiles/Makefile2:396: ошибка выполнения рецепта для цели «lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/all»
make[1]: *** [lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/all] Ошибка 2
Makefile:127: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by jaagr** [comment] 2016-11-09 09:03
You need a compiler with c++14 support. Try `cmake -DCMAKE_CXX_COMPILER=clang++ ..` if you have clang installed.

**Comment by jaagr** [comment] 2016-11-11 10:12
Closing, please reopen if the issue is still valid for you.

**Closed by jaagr** 2016-11-11 10:12 UTC
