### ISSUE TITLE
Tray bar problems

### ISSUE THREAD

**Issue by Quent42340** [jaagr/lemonbuddy#86] opened 2016-10-14 12:54 UTC
Sometimes the tray bar completely disappears, sometimes only the icons. It often happens after a full reload of bars (needed because of #85).

Other possible reasons:
- Wake up my laptop after standby
- When I run i3bar and kill it, the tray bar doesn't come back, same if I run the same bar twice with lemonbuddy

Don't know if it's related though, but sometimes icons doesn't update (I only have this problem with `nm-applet` but didn't noticed it with i3bar before...)

**Comment by jaagr** [comment] 2016-10-14 13:10
Thanks for reporting, I will look into it. See my comment in #85 about the `--reload` flag.

**Comment by Quent42340** [comment] 2016-10-14 13:16
I found a way to reproduce the problem:

Use my [script](https://github.com/Quent42340/dotfiles/blob/master/link/.config/lemonbuddy/launch) to run the bars, then execute this script once again, the tray bar will disappear, relaunch it, it will reappear, relaunch it and it will disappear, etc...

**Comment by jaagr** [comment] 2016-10-14 13:26
Could you try to send SIGKILL instead

`killall -9 lemonbuddy`

**Comment by Quent42340** [comment] 2016-10-14 13:29
Same issue

**Comment by jaagr** [comment] 2016-10-14 13:31
And what if you wait a second before launching the bars? I.e. add a `sleep 1` after killing the current bars.

**Comment by Quent42340** [comment] 2016-10-14 13:36
Since the `killall -9` the tray bar won't reappear at all, so I'll try and let you know once I'll restart X.

**Comment by jaagr** [comment] 2016-10-14 13:40
Hm, are you running anything else handling tray clients?

**Comment by Quent42340** [comment] 2016-10-14 13:45
Sometimes I run i3bar to see some informations I don't have implemented in my lemonbuddy config yet, but they're never running at the same time.

**Comment by jaagr** [comment] 2016-10-14 13:56
Then I guess this issue is caused by the tray client dismiss.. I'll be back when I've looked at it

**Comment by jaagr** [comment] 2016-10-14 22:56
Update: I've been able to reproduce the issue.

**Comment by jaagr** [comment] 2016-10-15 01:22
Could you verify if 6b0109e8dd4fb5bedb07bbfcc524e93a195830df fixes the problem with disappearing tray clients. It fixed the problem of quick reloading for me.

**Comment by jaagr** [comment] 2016-10-15 01:53
I'd also recommend adding this to your launch script, right after the `killall -q lemonbuddy`:

``` sh
# Wait until the processes have been shut down
while pgrep -x lemonbuddy >/dev/null; do sleep 1; done
```

**Comment by Quent42340** [comment] 2016-10-15 10:13
This problem seems to be fixed now, when I reload the bars using my script the tray bar won't disappear anymore, thanks! :)

**Comment by jaagr** [comment] 2016-10-15 10:45
Awesome, then I'll close this.

**Closed by jaagr** 2016-10-15 10:45 UTC
Labels: bug, confirmed
