### ISSUE TITLE
RAM / CPU overuse

### ISSUE THREAD

**Issue by Quent42340** [jaagr/lemonbuddy#87] opened 2016-10-14 12:57 UTC
It happened once that lemonbuddy used 200%+ CPU or more than 40% RAM (on 8 GB), I was running League of Legends when I got the 200%+ CPU problem, and it add a tray icon through wine so maybe this is related?

I think the RAM problem was after successive refreshes of the bars.

**Comment by jaagr** [comment] 2016-10-14 13:12
Could you please verify if this happens without the `--reload` flag

**Comment by Quent42340** [comment] 2016-10-14 13:13
Sure, I just removed it, will see if it happens again.

**Comment by Quent42340** [comment] 2016-10-14 13:32
I got the CPU problem again, it froze my i3, the process `lemonbuddy top` was using 100% CPU (the one with the tray bar, maybe this is related?)

**Comment by jaagr** [comment] 2016-10-14 13:35
Yes, deactivate the tray and I will try to find the issue...

**Comment by jaagr** [comment] 2016-10-14 13:35
I'm guessing it's dead locking somehow...

**Comment by jaagr** [comment] 2016-10-14 22:54
I'm having a hard time reproducing this. Could you please provide the following:

- The configuration file in use
- A list of active tray clients at the time the cpu frenzy
- Some details on your system (distro, wm, etc)

**Comment by Quent42340** [comment] 2016-10-15 10:08
- Config file: https://github.com/Quent42340/dotfiles/blob/master/link/.config/lemonbuddy/config
- List of active tray clients:
    - `nm-applet`
    - `redshift-gtk`
    - `dropbox`
- I'm using i3 on ArchLinux x86_64

I redirected output to log files now so as soon as I get this issue again I'll give you the logs

**Comment by Quent42340** [comment] 2016-10-17 06:38
I'm not totally sure this is tray-related, since yesterday, it happened two times right after a wake up of my computer from sleep, and my tray is disabled.

Initially, 25% CPU and 18% RAM were used, but RAM incremented itself (up to 25% after 2 min). So I tried a killall but the CPU went to 50% used, so I forced kill it...

I looked at the logs, there was literally nothing.

**Comment by jaagr** [comment] 2016-10-17 06:43
Next time, check the process with `strace -p <pid>` before killing it and see if you see something.

**Comment by jaagr** [comment] 2016-10-17 06:46
My computer never hibernates/sleeps so that's something i'd need to test to see if it could be related to that.

**Comment by Quent42340** [comment] 2016-10-17 19:49
Here is the full output of `strace -p <pid>`:

> $ strace -p 2998
> strace: Process 2998 attached
> rt_sigtimedwait([INT QUIT USR1 TERM], NULL, NULL, 8) = 15 (SIGTERM)
> fstat(2, {st_mode=S_IFREG|0644, st_size=2730, ...}) = 0
> lseek(2, 0, SEEK_CUR)                   = 0
> write(2, "lemonbuddy|warn   Termination si"..., 64) = 64
> futex(0x198a12c, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x198a100, 4512) = 1
> futex(0x198a100, FUTEX_WAKE_PRIVATE, 1) = 1
> futex(0x19e680c, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x19e67e0, 8980) = 1
> futex(0x19e67e0, FUTEX_WAKE_PRIVATE, 1) = 1
> futex(0x19ed17c, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x19ed150, 4460) = 1
> futex(0x19ed150, FUTEX_WAKE_PRIVATE, 1) = 1
> futex(0x19ed98c, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x19ed960, 4456) = 1
> futex(0x19ed960, FUTEX_WAKE_PRIVATE, 1) = 1
> poll([{fd=4, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=4, revents=POLLOUT}])
> writev(4, [{iov_base="\213\7\2\0j\32@\3", iov_len=8}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 8
> poll([{fd=4, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=4, revents=POLLOUT}])
> writev(4, [{iov_base="\4\0\2\0\2\0@\3", iov_len=8}], 1) = 8
> futex(0x1952a38, FUTEX_WAKE_PRIVATE, 1) = 1
> poll([{fd=4, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=4, revents=POLLOUT}])
> writev(4, [{iov_base="O\7\2\0T\0\0\0", iov_len=8}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 8
> poll([{fd=4, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=4, revents=POLLOUT}])
> writev(4, [{iov_base="\31\0\v\0)\1\0\0\0\0\2\0! \0\0)\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=44}], 1) = 44
> wait4(-1, 0x7ffc4075c660, WNOHANG, NULL) = 0

Before I killed it, the output was stopped in the middle of this line:

> rt_sigtimedwait([INT QUIT USR1 TERM], NULL, NULL,

**Comment by jaagr** [comment] 2016-10-17 23:32
the sigtimedwait is the main thread waiting for a termination signal, the rest is part of the shutdown routine.. did it not output anything after the last wait? if not I would guess that the X connection failed and that should probably be checked when shutting down

**Comment by Quent42340** [comment] 2016-10-18 06:34
After the last wait I only had a message like `**killed by SIGKILL**`

**Comment by jaagr** [comment] 2016-10-18 06:40
Did you send the SIGKILL or did it happen after a few seconds? If it happened after a few second it's because the controller failed to lock the mutex after 3 seconds which would indicate a dead lock..

**Comment by jaagr** [comment] 2016-10-18 09:33
I know the problem now... when building the release version of the project the compiler will optimize away something that makes it dead lock on termination.. but I haven't found what yet.. once I do I'll make it volatile and push a fix

**Comment by Quent42340** [comment] 2016-10-19 15:37
Since the last update (`2.0.1.r5.g56b4657`) lemonbuddy is continually running at ~1,5% CPU, making my fan quite noisy and annoying...

**Comment by jaagr** [comment] 2016-10-19 15:58
probably the spinlocking

**Comment by Vintodrimmer** [comment] 2016-10-25 08:45
Same for me. In my right panel there are following modules: volume battery memory cpu date.

This panel is constantly at the top in my htop CPU usage. If before it was ~0.7% (for 1-2 lemonbuddy instances), which was not that bad, now it's ~1.3%(for one. other 2 are still ~0.7% periodically).

If I recall correctly, it doesn't happen if only the date module is left, but I do need my battery charge indicator.

**Comment by jaagr** [comment] 2016-10-25 08:55
Are you using the last update?

**Comment by jaagr** [comment] 2016-10-25 09:05
If that doesn't improve your load you would need to decrease the number of updates and X requests... Increasing the interval for the cpu, memory and battery modules is a quick fix.

**Comment by Quent42340** [comment] 2016-10-26 10:01
Tried the last update a few minutes ago, the bottom bar was using >10% CPU with 5 custom/script modules, RAM, CPU and mpd
The top bar was ~1.4%, but sometimes `nm-applet` was using >35% CPU even if the tray bar is disabled, weird...

**Comment by jaagr** [comment] 2016-10-26 10:05
Sounds very weird.. Haven't experienced that cpu load... Are you using the `tail` option for non-tail scripts or a low interval value?  I will test the nm-applet to see if something's wrong.

**Comment by jaagr** [comment] 2016-10-26 10:13
Just tested your config and the cpu sure is spinning.

**Comment by jaagr** [comment] 2016-10-26 10:26
The default interval for `custom/script` was set to 0 which made non tailing scripts loop. Changed it to 2s but I'd recommend using a higher value for for the i3block scripts, since they won't change often anyway.

**Comment by Quent42340** [comment] 2016-10-28 09:58
I just updated from "4d24097" to the last version. I changed the `interval` field on all my `custom/script` and the bars seem fine. `nm-applet` is still using a lot of CPU sometimes but finally, I don't think it has anything related to lemonbuddy since the issue is present even when lemonbuddy isn't running.

The only problem left I see is that sometimes lemonbuddy just won't agree to be killed, and will use ~50% CPU, increasing RAM usage, etc... until I force kill it.

I reenabled the tray bar and will tell you if it causes any problem now.

**Comment by jaagr** [comment] 2016-10-28 10:19
I think that last issue is caused by a dead lock of a mutex. I haven't been able to replicate it though but another user has also reported the same issue (#123). I hope that it will be resolved with the new event loop that will use a "lock free" queue.

**Comment by jaagr** [comment] 2016-10-28 17:29
I found a bug that caused execution to block while a forked process was running. Might fix your termination issue.

**Comment by jaagr** [comment] 2016-10-31 01:03
Should be fixed with the new eventqueue.

**Closed by jaagr** 2016-10-31 01:03 UTC
Labels: bug, needs confirmation
